import { Navigation } from "./components/Navigation"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="es">
      <head>
        <title>Taberna de Mou</title>
        <meta charSet="utf-8" />
      </head>
      <body>
        <Navigation />
        {children}
        </body>
    </html>
  )
}
